include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-zwrt
PKG_VERSION:=3.5.6
PKG_RELEASE:=1

LUCI_TITLE:=ZWRT Theme Settings
LUCI_DEPENDS:=+luci-base

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
