name: Build LuCI Theme

on:
  push:
    branches: [ js ]
    paths:
      - 'luci-theme-kucat/**'
      - 'build_auto.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup & Build
        run: |
          chmod +x build_auto.sh
          sudo apt-get update
          sudo apt-get install -y wget binutils curl coreutils
          ./build_auto.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: bin/all-archs/*.ipk
          if-no-files-found: error

      # 可选：发布 Release
      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/js'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          generate_release_notes: true
          files: bin/all-archs/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
